name: "Detect snapshot"

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency: 
    group: detect-snapshot-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    detectSnapshot:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
            -   name: Detect SNAPSHOT
                run: scripts/analysis/detectSNAPSHOT.sh
