name: "Detect wrong settings"

on:
    pull_request:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency:
    group: detect-wrong-settings-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    detectWrongSettings:
        runs-on: ubuntu-22.04

        steps:
            -   uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v3
            -   name: Set up JDK 17
                uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Detect SNAPSHOT
                run: scripts/analysis/detectWrongSettings.sh
